using System.Collections;
using System.Collections.Generic;
using UnityEngine;
// TODO: this file is written for create a shield for the player to reduce damage
// need to communicate with "Health"
// the shield should has a value, and it also should be generated by an element


public class ShieldProtection : MonoBehaviour
{
    // Start is called before the first frame update
    [Range(0, 10)][Tooltip("The damage that the shield can suffer")] public float ShieldValue = 0;
    [Tooltip("The speed of shield recovering")] public float ShieldRecoverFrequency = 1;
    [Tooltip("The value of shield recovering")] public float ShieldRecoverValue = 0;
    private float updateShieldDDL;
    void Start()
    {
        //ShieldValue = 0;
        updateShieldDDL = Time.time;

    }

    // Update is called once per frame
    void Update()
    {
        //update new armer
        if(Time.time > updateShieldDDL)
        {
            updateShieldDDL += ShieldRecoverFrequency;
            ShieldValue += ShieldRecoverValue;

        }
    }

    public float reduce_damage(float damage)
    {
        if(damage > ShieldValue)
        {
            damage -= ShieldValue;
            ShieldValue = 0;
        }
        else
        {
            ShieldValue -= damage;
            damage = 0;
        }
        return damage;

    }
}
